Bpi\ApiBundle\Domain\Entity\UserFacet:
  repositoryClass: Bpi\ApiBundle\Domain\Repository\UserFacetRepository
  collection: UserFacet
  type: document

  fields:
    id:
      type: id
      id: true
    userId:
      type: string
    facetData:
      type: hash
