<?php

namespace Bpi\ApiBundle\Domain\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Bpi\ApiBundle\Domain\Entity\ChannelQuery;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends DocumentRepository
{
    /**
     * Find Channels by a query.
     *
     * @param ChannelQuery $query
     *
     * @return mixed
     */
    public function findByQuery(ChannelQuery $query)
    {
        return $query->executeByDoctrineQuery(
            $this->dm->createQueryBuilder($this->getClassName())
        );
    }

    public function findChannelsByUser($user)
    {
        $qb = $this->createQueryBuilder('Entity\Channel');
        $qb->addOr(
            $qb
                ->expr()
                ->field('channelAdmin')
                ->references($user)
        );
        $qb->addOr(
            $qb
                ->expr()
                ->field('channelEditors')
                ->includesReferenceTo($user)
        );
        $qb->addAnd(
            $qb
                ->expr()
                ->field('channelDeleted')
                ->equals(false)
        );

        $result = $qb
            ->getQuery()
            ->execute()
        ;

        $count = $result->count();
        return ($count === 0) ? null : $result;
    }

    public function findByChannelQuery(ChannelQuery $query)
    {
        return $query->executeByDoctrineQuery(
            $this->dm->createQueryBuilder($this->getClassName())
        );
    }
}
