<?php

namespace Bpi\ApiBundle\Domain\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends DocumentRepository
{
    /**
     * Helper method, determine if channel name is free to use for new channel
     *
     * @param $channelName string name of channel which should be checked on duplicates
     * @return bool is name of channel free
     */
    public function findSimilarByName($channelName)
    {
        $result = $this->findOneByChannelName($channelName);
        return ($result) ? true : false;
    }

    public function findChannelsByUser($user)
    {
        $qb = $this->createQueryBuilder('Entity\Channel');
        $qb->addOr(
            $qb
                ->expr()
                ->field('channelAdmin')
                ->references($user)
        );
        $qb->addOr(
            $qb
                ->expr()
                ->field('channelEditors')
                ->includesReferenceTo($user)
        );

        $result = $qb
            ->getQuery()
            ->execute()
        ;

        $count = $result->count();
        return ($count === 0) ? null : $result;
    }
}
