<?php

namespace Bpi\ApiBundle\Domain\Repository;

use Bpi\ApiBundle\Domain\Entity\ChannelFacet;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ChannelFacetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelFacetRepository extends DocumentRepository
{

    /**
     * @var array of applied filters
     */
    private $filters;

    /**
     * @var string applied logical operator
     */
    private $logicalOperator;

    /**
     * Prepare facets for each channel
     *
     * @param $channel
     */
    public function prepareFacet($channel) {
        $facet = new ChannelFacet();

        $agency = $channel->getChannelAdmin()->getUserAgency();

        $data = array(
            'agency_id' => $agency->getPublicId(),
        );

        $facet->setChannelId($channel->getId());
        $facet->setFacetData((object)$data);

        $this->dm->persist($facet);
        $this->dm->flush();
    }

    /**
     * Build facets and get channel ids by which will be made request to DB
     *
     * @param array $filters applied filters
     * @param string $logicalOperator by default OR could be AND
     * @return \StdClass
     *  contain array of built facets and array of channel ids
     */
    public function getFacetsByRequest($filters = array(), $logicalOperator = 'OR')
    {
        $facets = array();
        $channelIds = array();

        $this->filters = $filters;
        $this->logicalOperator = $logicalOperator;

        $qb = $this->createQueryBuilder('Entity\ChannelFacet');

        $filteredChannels = $this->iterateTerms($qb);
        foreach ($filteredChannels as $key => $channel) {
            $id = $channel->getChannelId();
            if (isset($id) && !empty($id)) {
                $channelIds[] = $id;
            }
        }

        $qb->map('
                function() {
                    for (var i in this.facetData) {
                        if (i == "tags") {
                            for (var j in this.facetData[i]) {
                                var key = {
                                    facetName: "tags",
                                    facetValue: this.facetData[i][j]
                                }
                                emit(key, 1);
                            }
                        } else if (i == "channels") {
                            for (var j in this.facetData[i]) {
                                var key = {
                                    facetName: "channels",
                                    facetValue: this.facetData[i][j]
                                }
                                emit(key, 1);
                            }
                        } else {
                            var key = {
                                facetName: i,
                                facetValue: this.facetData[i]
                            }
                            emit(key, 1);
                        }
                    }
                }
            ')
            ->reduce('
                function(key, values) {
                    var sum = 0;
                    for(var i in values) {
                        sum += values[i];
                    }
                    return sum;
                };
            ')
        ;

        $result = $this->iterateTerms($qb);
        foreach ($result as $facet) {
            if ($facet['_id']['facetName'] == 'agency_id') {
                $agency = $this->dm->getRepository('BpiApiBundle:Aggregate\Agency')->loadUserByUsername($facet['_id']['facetValue']);
                $facets['agency_id'][$facet['_id']['facetValue']]['agencyName'] = $agency->getName();
                $facets['agency_id'][$facet['_id']['facetValue']]['count'] = $facet['value'];
            } else {
                $facets[$facet['_id']['facetName']][$facet['_id']['facetValue']] = $facet['value'];
            }
        }

        $channelFacets = new \StdClass();
        $channelFacets->facets = $facets;
        $channelFacets->channelIds = $channelIds;

        return $channelFacets;
    }

    /**
     * Iterate over applied filters and make request to db
     * @param $qb object of query builder
     * @return mixed
     *  array of facets or facet entities
     */
    private function iterateTerms($qb)
    {
        if (!empty($this->filters)) {
            foreach ($this->filters as $filter_name => $values) {
                $terms = array();
                foreach ($values as $value) {
                    switch ($filter_name) {
                        // Agency, tags
                        default :
                            $terms[] = $value;
                            break;
                    }
                }

                switch (strtoupper($this->logicalOperator)) {
                    case 'AND' :
                        $qb->addAnd($qb->expr()->field('facetData.' . $filter_name)->in($terms));
                        break;

                    default :
                        $qb->addOr($qb->expr()->field('facetData.' . $filter_name)->in($terms));
                        break;
                }
            }
        }

        $result = $qb
            ->getQuery()
            ->execute()
        ;

        return $result;
    }

    /**
     * Update facets after agency changes.
     *
     * @param $changes
     * @return bool
     */
    public function updateFacet($changes)
    {
        $qb = $this->dm->createQueryBuilder('BpiApiBundle:Entity\ChannelFacet')
            ->update()
            ->multiple(true)
        ;

        if (isset($changes['channelId'])) {
            $qb->field('channelId')->equals($changes['channelId']);
        }

        foreach ($changes as $changedValue => $changed) {
            if (is_array($changed) && isset($changed['newValue']) && isset($changed['oldValue'])) {
                $qb->field('facetData.' . $changedValue)->set($changed['newValue']);
                $qb->field('facetData.' . $changedValue)->equals($changed['oldValue']);
            } elseif ('tags' === $changedValue) {
                $qb->field('facetData.' . $changedValue)->set($changed);
            }

            if ('agency_id' === $changedValue && is_string($changed)) {
                $qb->field('facetData.' . $changedValue)->equals($changed);
            } else {
                $qb->field('facetData.' . $changedValue)->set($changed['newValue']);
                $qb->field('facetData.' . $changedValue)->equals($changed['oldValue']);
            }
        }

        $qb
            ->getQuery()
            ->execute()
        ;

        return true;
    }

    /**
     * Remove facet by channelId.
     *
     * @param $channelId
     */
    public function delete($channelId) {
        $this->createQueryBuilder('BpiApiBundle:Entity\ChannelFacet')
            ->remove()
            ->field('channelId')->equals($channelId)
            ->getQuery()
            ->execute()
        ;
    }
}
