<?php

namespace Bpi\ApiBundle\Domain\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends DocumentRepository
{
    /**
     * Helper method, determine if channel name is free to use for new channel
     *
     * @param $channelName string name of channel which should be checked on duplicates
     * @return bool is name of channel free
     */
    public function findSimilarByName($channelName)
    {
        $em = $this->createQueryBuilder('Entity\Channel')
            ->field('channelName')
            ->equals($channelName)
        ;

        $result = $em
            ->getQuery()
            ->getSingleResult()
        ;

        return ($result) ? true : false;
    }
}
