<?php

namespace Bpi\ApiBundle\Domain\Repository;

use Bpi\ApiBundle\Domain\Entity\UserFacet;
use Bpi\ApiBundle\Domain\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\Query\Builder as QueryBuilder;

/**
 * UserFacetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFacetRepository extends DocumentRepository
{

    /**
     * @var array of applied filters
     */
    private $filters;

    /**
     * @var string applied logical operator
     */
    private $logicalOperator;

    /**
     * Prepare facet for a user.
     *
     * @param User $user
     */
    public function prepareFacet(User $user) {
        $facet = new UserFacet();

        $agency = $user->getUserAgency();
        $data = (object)array(
            'agency_id' => $agency->getPublicId(),
        );

        $facet->setUserId($user->getId());
        $facet->setFacetData($data);

        $this->dm->persist($facet);
        $this->dm->flush();
    }

    /**
     * Build facets and get user ids by which will be made request to DB
     *
     * @param array $filters applied filters
     * @param string $logicalOperator by default OR could be AND
     * @return \StdClass
     *  contain array of built facets and array of user ids
     */
    public function getFacetsByRequest($filters = array(), $logicalOperator = 'OR')
    {
        $userIds = array();

        $this->filters = $filters;
        $this->logicalOperator = $logicalOperator;

        $qb = $this->createQueryBuilder();

        $filteredUsers = $this->iterateTerms($qb);
        foreach ($filteredUsers as $key => $user) {
            $id = $user->getUserId();
            if (!empty($id)) {
                $userIds[] = $id;
            }
        }

        $qb->map('
                function() {
                    for (var i in this.facetData) {
                        if (i == "tags") {
                            for (var j in this.facetData[i]) {
                                var key = {
                                    facetName: "tags",
                                    facetValue: this.facetData[i][j]
                                }
                                emit(key, 1);
                            }
                        } else {
                            var key = {
                                facetName: i,
                                facetValue: this.facetData[i]
                            }
                            emit(key, 1);
                        }
                    }
                }
            ')
            ->reduce('
                function(key, values) {
                    var sum = 0;
                    for(var i in values) {
                        sum += values[i];
                    }
                    return sum;
                };
            ')
        ;

        $facets = array();
        $result = $this->iterateTerms($qb);
        foreach ($result as $facet) {
            if ($facet['_id']['facetName'] == 'agency_id') {
                $agency = $this->dm->getRepository('BpiApiBundle:Aggregate\Agency')->loadUserByUsername($facet['_id']['facetValue']);
                $facets['agency_id'][$facet['_id']['facetValue']]['agencyName'] = $agency->getName();
                $facets['agency_id'][$facet['_id']['facetValue']]['count'] = $facet['value'];
            } else {
                $facets[$facet['_id']['facetName']][$facet['_id']['facetValue']] = $facet['value'];
            }
        }

        return (object)array(
            'facets' => $facets,
            'userIds' => $userIds,
        );
    }

    /**
     * Iterate over applied filters and make request to db
     * @param $qb object of query builder
     * @return mixed
     *  array of facets or facet entities
     */
    private function iterateTerms(QueryBuilder $qb)
    {
        if (!empty($this->filters)) {
            foreach ($this->filters as $filter_name => $values) {
                $terms = array();
                foreach ($values as $value) {
                    switch ($filter_name) {
                        default :
                            $terms[] = $value;
                            break;
                    }
                }

                switch (strtoupper($this->logicalOperator)) {
                    case 'AND' :
                        $qb->addAnd($qb->expr()->field('facetData.' . $filter_name)->in($terms));
                        break;

                    default :
                        $qb->addOr($qb->expr()->field('facetData.' . $filter_name)->in($terms));
                        break;
                }
            }
        }

        $result = $qb
            ->getQuery()
            ->execute()
        ;

        return $result;
    }

    /**
     * Update facets after agency changes.
     *
     * @param $changes
     * @return bool
     */
    public function updateFacet($changes)
    {
        $qb = $this->dm->createQueryBuilder()
            ->update()
            ->multiple(true)
        ;

        if (isset($changes['nodeId'])) {
            $qb->field('nodeId')->equals($changes['nodeId']);
        }

        foreach ($changes as $changedValue => $changed) {
            if (is_array($changed) && isset($changed['newValue']) && isset($changed['oldValue'])) {
                $qb->field('facetData.' . $changedValue)->set($changed['newValue']);
                $qb->field('facetData.' . $changedValue)->equals($changed['oldValue']);
            } elseif ('tags' === $changedValue) {
                $qb->field('facetData.' . $changedValue)->set($changed);
            }

            if ('agency_id' === $changedValue && is_string($changed)) {
                $qb->field('facetData.' . $changedValue)->equals($changed);
            } else {
                $qb->field('facetData.' . $changedValue)->set($changed['newValue']);
                $qb->field('facetData.' . $changedValue)->equals($changed['oldValue']);
            }
        }

        $qb
            ->getQuery()
            ->execute()
        ;

        return true;
    }

  /**
   * Remove facet by userId.
   *
   * @param $nodeId
   */
    public function delete($nodeId) {
        $this->createQueryBuilder()
            ->remove()
            ->field('nodeId')->equals($nodeId)
            ->getQuery()
            ->execute()
        ;
    }
}
