<?php

namespace Bpi\ApiBundle\Domain\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    /**
     * Check if User with such internal name exitst
     *
     * @param string $internalName
     * @return bool
     */
    public function findSimilarUserByInternalName($internalName)
    {
        $query = $this->createQueryBuilder('Entity\Channel')
            ->field('internalUserName')
            ->equals($internalName)
        ;

        $result = $query
            ->getQuery()
            ->getSingleResult()
        ;

        return ($result) ? true : false;
    }
}
