<?php

namespace Bpi\ApiBundle\Tests;

class AbstractFixtureAwareBpiTest extends AbstractBaseBpiTest
{
    /**
     * {@inheritdoc}
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * Gets an array of fixtures to be managed.
     *
     * @return array
     */
    public function getFixtures()
    {
        return [];
    }
}
