<?php

namespace Bpi\ExtReviewsBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ReviewBpiNodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewBpiNodeRepository extends DocumentRepository
{
}